#
# LOCAL
#
kevit.login.company=KE
crypto.key=KEVITTOULVAC2019

# Smartro
pg.smartro.cancelActionUrl=https://pay.smilepay.co.kr/cancel/payCancelNVProcess.jsp
# BillGate
pg.billgate.config=/csms/pg/conf/config.ini
# Map
map.kakaoMapKey=ee919124706bb1c0341e9bf6db0be78d
# Naver
naver.clientId=did0h5u7ap
naver.clientSecret=bCBpVkrs7t8hNEvDc5BXS3m44ogO9lR3d4nMIE39
# PHONE
phone.ev=10012002

# EMAIL
email.SMTP_ID=??
email.SMTP_PS=??
email.HOST_ADDR=bckim@kevit.co.kr

# FILE
file.rootFolder=/
file.tmpFolder=csms/store/temp
file.storageFolder=csms/store/upload
file.checkListFolder=csms/store/checklist
file.fwFolder=csms/store/fw
file.ocpp=csms/store/ocpp

# QR
qr.file=/csms/store/open/resources/qrcode/
qr.url=https://www.kevit.co.kr/mobile/guest/qr/

# KECO
keco.project.devMode=true
keco.log.console.print = true
keco.system.static.webservice=https://www.kevit.co.kr
keco.bid=KE
keco.bkey=KE000aaabbbcccdd
# DEV
keco.host=http://10.101.160.11
# OP
#keco.host=http://10.101.160.34