-- TB_CHCP001 (충전소), TB_CUCU001 (고객)에 단지 FK 컬럼 추가

-- TB_ORCX001.CX_ID는 utf8mb4/utf8mb4_unicode_ci로 생성됨. FK 컬럼의 charset/collation이
-- 다르면 InnoDB가 제약 추가를 거부하므로(Error 1215/150) 명시적으로 맞춰준다.
ALTER TABLE TB_CHCP001
    ADD COLUMN CX_ID CHAR(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '단지아이디' AFTER CP_LOC;

ALTER TABLE TB_CHCP001
    ADD CONSTRAINT FK_CHCP001_CX_ID FOREIGN KEY (CX_ID) REFERENCES TB_ORCX001 (CX_ID);

ALTER TABLE TB_CUCU001
    ADD COLUMN CX_ID CHAR(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '단지아이디' AFTER CO_ID;

ALTER TABLE TB_CUCU001
    ADD CONSTRAINT FK_CUCU001_CX_ID FOREIGN KEY (CX_ID) REFERENCES TB_ORCX001 (CX_ID);
