-- TB_CUCU001 (고객)의 DONG_HO 컬럼을 DONG, HO로 분리

ALTER TABLE TB_CUCU001
    ADD COLUMN DONG VARCHAR(20) NULL COMMENT '거주지 동' AFTER EMAIL,
    ADD COLUMN HO   VARCHAR(20) NULL COMMENT '거주지 호' AFTER DONG;

UPDATE TB_CUCU001
   SET DONG = CASE WHEN DONG_HO LIKE '%-%' THEN SUBSTRING_INDEX(DONG_HO, '-', 1) ELSE DONG_HO END,
       HO   = CASE WHEN DONG_HO LIKE '%-%' THEN SUBSTRING_INDEX(DONG_HO, '-', -1) ELSE NULL END
 WHERE DONG_HO IS NOT NULL;

ALTER TABLE TB_CUCU001
    DROP COLUMN DONG_HO;
