server:
  port: 8900

spring:
  application:
    name: ocpp16-daemon
  datasource:
    # url: jdbc:mysql://121.170.152.235:16000/LOCAL_CSMS
    # username: lcsmsoper
    # password: 3neiwQa0!
    url: jdbc:mysql://localhost:3306/LOCAL_CSMS?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kevit
    password: kevit

logging:
  level:
    kr.co.kevit.localcsms.ocpp: DEBUG

mybatis:
  mapper-locations: classpath*:kr/co/kevit/localcsms/**/dao/mr/*_sql.xml
  type-handlers-package: kr.co.kevit.localcsms.common.util.typehandler
  type-aliases-package: >
    kr.co.kevit.localcsms.common.domain,
    kr.co.kevit.localcsms.common.shared,
    kr.co.kevit.localcsms.common.util.typehandler,
    kr.co.kevit.localcsms.authority.entity.domain,
    kr.co.kevit.localcsms.authority.entity.shared,
    kr.co.kevit.localcsms.organization.entity.domain,
    kr.co.kevit.localcsms.organization.entity.shared,
    kr.co.kevit.localcsms.customer.entity.domain,
    kr.co.kevit.localcsms.customer.entity.shared,
    kr.co.kevit.localcsms.product.entity.domain,
    kr.co.kevit.localcsms.product.entity.shared,
    kr.co.kevit.localcsms.charger.entity.domain,
    kr.co.kevit.localcsms.charger.entity.shared,
    kr.co.kevit.localcsms.recharger.entity.domain,
    kr.co.kevit.localcsms.recharger.entity.shared,
    kr.co.kevit.localcsms.system.entity.domain,
    kr.co.kevit.localcsms.system.entity.shared,
    kr.co.kevit.localcsms.smartcharging.entity.domain,
    kr.co.kevit.localcsms.smartcharging.entity.shared
  configuration:
    map-underscore-to-camel-case: true

