<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>kr.co.kevit.ocpp</groupId>
    <artifactId>kevit-ocpp</artifactId>
    <version>0.0.1</version>
  </parent>
  <artifactId>ocpp-domain</artifactId>
  <packaging>pom</packaging>
  <modules>
  	<module>ocpp16-core-domain</module>
  	<module>ocpp16-lc-domain</module>
  </modules>
</project>
