CREATE TABLE IF NOT EXISTS TB_RCRS001 (
    RSV_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '예약 ID',
    CP_ID CHAR(9) NOT NULL COMMENT '충전기 ID',
    CS_ID CHAR(2) NOT NULL COMMENT '충전소 ID',
    EXP_DT DATETIME NOT NULL COMMENT '만료 일시',
    CUT_CRD_NO VARCHAR(16) NOT NULL COMMENT '인증 카드 번호',
    PARENT_CRD_NO VARCHAR(16) DEFAULT NULL COMMENT '부모 카드 번호',
    STATUS CHAR(6) NOT NULL COMMENT '상태 (RSVT01: 예약, RSVT02: 예약취소)',
    REG_DT DATETIME NOT NULL COMMENT '등록 일시',
    REG_ID CHAR(9) NOT NULL COMMENT '등록자 ID',
    UPD_DT DATETIME NOT NULL COMMENT '수정 일시',
    UPD_ID CHAR(9) NOT NULL COMMENT '수정자 ID'
) COMMENT='충전기 예약 관리 테이블';
