CREATE TABLE TB_SYRM001 (
    UUID       VARCHAR(36)   NOT NULL COMMENT 'UUID',
    ACT_NM     VARCHAR(30)   NOT NULL COMMENT 'Action Name',
    REQ_PLD    VARCHAR(255)  NOT NULL COMMENT 'Request Payload',
    STATUS     CHAR(6)       NOT NULL COMMENT '상태 (RMST01:요청, RMST02:응답, RMST03:실패)',
    RES_PLD    VARCHAR(255)           COMMENT 'Response Payload',
    OCPP_VER   VARCHAR(10)            COMMENT 'OCPP 버전 (1.6 / 2.0.1)',
    KEY_ID     VARCHAR(36)   DEFAULT NULL COMMENT '키 ID',
    REG_DT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='원격 로그';

-- 기존 테이블에 컬럼 추가 시:
-- ALTER TABLE TB_SYRM001 ADD COLUMN OCPP_VER VARCHAR(10) NULL COMMENT 'OCPP 버전 (1.6 / 2.0.1)' AFTER RES_PLD;
-- ALTER TABLE TB_SYRM001 ADD COLUMN KEY_ID VARCHAR(36) DEFAULT NULL COMMENT '키 ID' AFTER OCPP_VER;
