<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>recharging</artifactId>
        <groupId>kr.co.kevit.localcsms</groupId>
        <version>0.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>recharging-process</artifactId>

    <dependencies>
        <dependency>
            <groupId>kr.co.kevit.localcsms</groupId>
            <artifactId>recharging-entity</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>kr.co.kevit.localcsms</groupId>
            <artifactId>charger-entity</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>kr.co.kevit.localcsms</groupId>
            <artifactId>common-util</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
        	<groupId>kr.co.kevit.localcsms</groupId>
        	<artifactId>common-testcase</artifactId>
        	<version>0.0.1</version>
        	<scope>test</scope>
        </dependency>
        <dependency>
        	<groupId>kr.co.kevit.localcsms</groupId>
        	<artifactId>customer-entity</artifactId>
        	<version>0.0.1</version>
        </dependency>
        <dependency>
        	<groupId>kr.co.kevit.localcsms</groupId>
        	<artifactId>organization-entity</artifactId>
        	<version>0.0.1</version>
        </dependency>
        <dependency>
        	<groupId>kr.co.kevit.localcsms</groupId>
        	<artifactId>common-entity</artifactId>
        	<version>0.0.1</version>
        </dependency>
    </dependencies>

</project>